### ISSUE TITLE
Possible to get untextured dirt with chisel

### ISSUE THREAD

**Issue by SixOneThree** [Pokefenn/Chisel#13]
Forge Version: 10.12.2.1124
Minecraft Version: 1.7.2
Chisel Version: 1.5.4f

It is possible to get untextured dirt by using a chisel

![image](https://cloud.githubusercontent.com/assets/7621888/3281218/bb64f712-f49c-11e3-8a55-affb89c6d8ee.png)

![image](https://cloud.githubusercontent.com/assets/7621888/3281244/7b187b56-f49d-11e3-8ade-05ed36de78a3.png)

**Comment by Pokefenn** [comment]
Fixed.
