### ISSUE TITLE
Broken texture connection on some blocks.

### ISSUE THREAD

**Issue by SmiVan** [Pokefenn/Chisel#14]
Forge Version: 10.12.2.1121
Chisel Version: 1.5.4f

Many blocks have broken texture connection, for example Obsidian Snakestone Body and Obsidian Snakestone Head. This problem also occurs with bookshelves.

![2014-06-16_12 43 53](https://cloud.githubusercontent.com/assets/7703934/3284906/49d9035e-f532-11e3-8bbf-5361f0314c00.png)

I guess this is related to the 1.7.2 texture bug (like with the sides of beds being rotated incorrectly).

**Comment by ghost** [comment]
Yep, fixed in 1.7.10pre4.
