### ISSUE TITLE
Real localization support

### ISSUE THREAD

**Issue by labpaw** [Pokefenn/Chisel#16]
Currently all blocks names and tooltips hardcoded in class file. This should be fixed.

**Comment by Pokefenn** [comment]
It's on my todo list, currently that requires manually changing the names on EVERY block, and most importantly, the tooltips, which is a monstrous task, and not something i could just do simply.

**Comment by Vexatos** [comment]
:+1:

**Comment by ghost** [comment]
Want me to give that a shot?  I have done localization support before and have nothing to do tonight...

Edit: Or for a long time, it seems :P

Edit 2: Too late!  Already started working on it.  Will submit a pull soon...
