### ISSUE TITLE
[1.7.2] Error on startup

### ISSUE THREAD

**Issue by MrSapient** [Pokefenn/Chisel#20]
http://pastebin.com/duJJqp0K

Mod Version: 1.5.4g
Forge: 10.12.2.1133

**Comment by ghost** [comment]
That is Chisel failing to find another mod for compatibilty, therefore returning that error.  It is not an issue at all; just Chisel saying you don't have Artifice.  That is, of course, you aren't crashing.

**Comment by MrSapient** [comment]
Nope not crashing .. Just spams the console
