### ISSUE TITLE
Can't cross threshold

### ISSUE THREAD

**Issue by Teslakoyal** [Pokefenn/Chisel#22]
So I have a storage building built out of Concrete blocks and factory blocks. If I have my doorway framed in factory blocks I can't cross the threshold
![2014-07-02_16 24 50](https://cloud.githubusercontent.com/assets/5156079/3463816/cc5627e2-0240-11e4-8523-10967b7b657b.png)
The picture shows the threshold I am talking about. If I take out the floor blocks and extend the concrete blocks out to be the base of the opening I can pass through just fine. also if i have concrete blocks right up to a door or stairs I can't go up the stairs or pass through an open door.
I am using the latest 1.7.2 version of the mod

**Comment by Pokefenn** [comment]
Hrm, might have a idea why this is happening, I'll look into it when im not at school :p

**Comment by Pokefenn** [comment]
Looking into it, its because of the AABB to the block that other blocks do not have. The same thing actually happens with soul sand iirc. Dunno if i can fix it without changing how the block works :P
