### ISSUE TITLE
Chisel 1.5.5 crashing on server

### ISSUE THREAD

**Issue by Yabdat** [Pokefenn/Chisel#24]
Tried to run the 1.5.5 update with Forge 1160. Works fine in singleplayer, but if i try it on a  server it crashes.

http://pastebin.com/Hi1V8AsR

**Comment by Pokefenn** [comment]
Welp... the weird locale stuff zombiepig used is client side only... T.T
Let me look into this for a second...

**Comment by ghost** [comment]
Woops!!  Sorry- completely forgot that was client-side only!!

~~I had been working on guis previously, so my mind skipped to using I18n without thinking about the server- derpy me.  Again, sorry!!~~

Well, turns out you don't even use I18n for guis... I am such a fucking noob.

**Comment by Pokefenn** [comment]
Hehe, its fine :P
I should have been not lazy and forced/asked someone to test it on a server anyways xD
