### ISSUE TITLE
Feature Request:  Support for Chisel tools in Tinkers Construct and Carpenter's Blocks

### ISSUE THREAD

**Issue by MikeBurk** [Pokefenn/Chisel#25]
Just a feature request, and I would be happy to assist with it if it is decided to be a desirable feature:
- Support Tinker's Constructs Chisels for opening the Chisel GUI and taking damage on chiseling
- Optional configuration for enabling / disabling the default chisel
- Support the Carpenter's Blocks chisel for opening the Chisel GUI

This is such a fantastic use of the chisel tool concept, it would be great to help offer a way of tying them together to aid modpack builders in unifying a much more vibrant chiseling experience.

**Comment by Pokefenn** [comment]
This would be on their end, and would be more of a feature conflict in the mods. It would be impossible for me to add it in anyways, unless i went crazy with asm <,<
