### ISSUE TITLE
Project Red Marble compatibility is broken

### ISSUE THREAD

**Issue by Raspen0** [Pokefenn/Chisel#26]
Project Red Marble compatibility is broken in the 1.7 version.
EDIT: It also seems to be broken in the last 1.6 version

You can't chisel Project Red Marble and you also can't turn Chisel Marble into Project Red Marble

I tried to fix it myself in eclipse but the layout of the project red blocks seem to have  been changed and the format of the block class been changed to scala.
I hope the above information helps you.

**Comment by Pokefenn** [comment]
Ok, that should be it fixed in the latest commit. Sorry that i took so long to get around to it, had to do it differently because the scala layout. Haven't tested yet, so reopen if the issue persists.

**Comment by Raspen0** [comment]
EDIT: I didn't see that you made a new commit, It works now so just ignore what i said below :)

I've compiled Chisel but it still doesn't work

I'm currently using a temporarily  workaround with Minetweaker adding Project Red Marble to the OreDictionairy

I can't reopen the issue if you closed it, so i hope you still see this

**Comment by trabpukcip** [comment]
Tested with both PR 4.4.5.44 and the just released 4.4.6.45 just in case something else changed.

![2014-08-11_23 23 21](https://cloud.githubusercontent.com/assets/4687400/3878083/ff676e3a-216b-11e4-8079-00cc871b959e.png)
