### ISSUE TITLE
Missing sounds

### ISSUE THREAD

**Issue by Techokami** [Pokefenn/Chisel#29]
Step on a Factory block:
[Client thread/WARN]: Unable to play unknown soundEvent: step.chisel:metal

Step on a Holystone block:
[Client thread/WARN]: Unable to play unknown soundEvent: step.chisel:holystone

Step on a Temple block:
[Client thread/WARN]: Unable to play unknown soundEvent: minecraft:step.dig.stone

All blocks include chiseled variants as well.

**Comment by ghost** [comment]
I have same issue. In the 1.6.4 these sounds works.

**Comment by ghost** [comment]
When you add to StepSoundEx.java this code:

@Override
public String getStepResourcePath()
{
return this.stepName;
}

Issue will be fixed.
