### ISSUE TITLE
What a mess...Another error!

### ISSUE THREAD

**Issue by tambry** [Pokefenn/Chisel#3]
I shall fix up some of your stuff.

**Comment by Pokefenn** [comment]
Yup, this code is full of so many confusing errors/bad coding practices, I've cleaned up the majority of them when i first took it over, you have no idea how bad it was xD

**Comment by tambry** [comment]
@Pokefenn If you don't mind I will do a quite a re-boot of your workspace, include build scripts and make a proper .gitignore and add some .gitattributes too...

**Comment by Pokefenn** [comment]
If you want :p
I've always just manually done everything xD

**Comment by tambry** [comment]
@Pokefenn There you go, first pull request with Gradle things.
More to follow.

**Comment by tambry** [comment]
@Pokefenn Yeah, the code looks horrible. Got it compiling and not crashing.
Here's and actual WORKING version for you to release until I wrap up tomorrow: 
http://www.mediafire.com/download/5tx3wbx5cq0k1jp/Chisel-1.7.2-1.6.jar

NOTE: I have changed your folder structure and build script quite a bit so you need to re-add the Gradle project probably (and maybe re-decompile)

**Comment by Pokefenn** [comment]
What are the changes? Can you push to git to make sure that i can see everything is ok? :)

**Comment by tambry** [comment]
@Pokefenn Under changes it's pretty much changing of folder structure :D Will commit now.

**Comment by Pokefenn** [comment]
I don't really see any need in changing the folder structure >.>

**Comment by tambry** [comment]
@Pokefenn Seems to work OK. Now build a build that actually works.
