### ISSUE TITLE
Strange issues with "Chisel" item

### ISSUE THREAD

**Issue by labpaw** [Pokefenn/Chisel#30]
1) Chisel can't break blocks. At all.
2) If you break a block with Chisel in Creative, block disappear but you can't stand on where there was a block.
3) Chisel GUI has extra spaces for items. -> http://i.imgur.com/uqlNOTR.jpg
4) Chisel GUI can't be translated. (Carve blocks)
Tested on SSP, MC 1.7.10 and Forge 1189, 1199

**Comment by Pokefenn** [comment]
That's intended, to do with a currently broken system for changing blocks.
Un-intended side effect of the above, not really enough of a "bug" to change things.
The gui will expand if there is more than the base amount of things to chisel, got me off guard at the start also :P
Will add that in :)
