### ISSUE TITLE
Lavastone seem to act like glass

### ISSUE THREAD

**Issue by EoD** [Pokefenn/Chisel#31]
Lavastone acts like glass for me. That means: I cannot place objects like tracks on it, nor do mobs spawn on it.

Is this intentional? Could you add an option to the config file to change the behavior?

**Comment by EoD** [comment]
Apparently it is due to BlockTexturedOre.java line 30:

``` java
    @Override
    public boolean renderAsNormalBlock()
    {
        return false;
    }
```

Overriding this method inside BlockLavastone.java allows the following
![2014-08-07_21 43 33](https://cloud.githubusercontent.com/assets/293499/3848031/b15703ac-1e6b-11e4-9fb8-4dfa56f62c80.png)

I am not very familiar with modding in mc, so I don't know if this has any consequences which I am not aware of. Why is this renderAsNormalBlock() in BlockTexturedOre.java in the first place?

**Comment by Pokefenn** [comment]
Iirc renderAsNormalBlock needed for the connected texture blocks (not 100% sure, but I'll just go with it) 
Since this isn't needed, ill over ride it in this class :)

**Comment by EoD** [comment]
In case you are interested, I added this change to the version which is compatible with 1.7.2: https://github.com/EoD/Chisel/releases/tag/v1.5.4h
