### ISSUE TITLE
Block placing places <error> blocks.

### ISSUE THREAD

**Issue by SythsGod** [Pokefenn/Chisel#34]
So this issue started happening after I updated my recently created server (although I hadn't used Chisel before the update anyway). It happens sometimes when placing a chisel block (Alligned Cobblestone Bricks and Huge Cobblestone Tiles in this case), it changes the block into an <"error"> block (what WAILA says). It doesn't happen with every block that's placed and after the blocks are mined up again (which is possible) and placed down in the same blockspace it works fine.

Current forge version: 10.13.0.1197

A list of mods on the server: http://puu.sh/aLAlI/4d689a1b02.png

I also have InventoryTweaks installed on the client.

Image of the problem (Errored blocks and none errored blocks, all placed without removing before): http://puu.sh/aLB6T/3d1e11d1ee.png

I hope you can figure out what's going on, it didn't show up on the any log though.

If there's something I missed, be sure to let me know!

Good luck,

Syths

**Comment by Pokefenn** [comment]
First off, thank you for the detailed bug report, It's so rare to get a decently done one.

Second off, I have no idea what's happening. I've heard of people having this issue on occasion, but i have been completely unable to reproduce it myself. I have tried on a server, development environment and single player to no avail. I see no mods that could be causing the issue, so that's out of the window :/

So yeah... I have no idea, sorry about that :l 
Gonna leave the issue open for if anyone has more leads to the issue.

**Comment by F4ble2** [comment]
Same Problem here http://s7.directupload.net/images/140811/fjxiv2tk.png

after updating a few mods alongside chisel, not sure if it is chisel that caused the problem.

when i place a sandstone slab it turns to a stone slab .... not everytime bit sometimes

can it be a forge problem? i use forge 10.13.0.1198

**Comment by SythsGod** [comment]
To F4ble2 his comment:

After writing my previous comment, I also needed to place some cobblestone slabs and they turned into stone slabs aswell.

This, however, doesn't only account to regular building blocks. Placing a magmatic dynamo (from CoFH's Thermal Expansion) changes it, sometimes, into a regular old steam dynamo. Same's happened with Extra Utilities 'liquid' nodes, they transform back to transfer nodes on placement.

Perhaps it is indeed a Forge problem? 
I'm still on version 1197.

As for my server:
I added almost every OpenMod and updated Forestry. ProjectRed is also a thing on there. Still happens.

On another note, water and lava seems to recreate it's own source blocks when it flows? Just for an example - I had an underwater base and had to replace the wall with glass, after removing 1 block water started flowing in. I quickly closed it (because I knew this might happen) and it did happen. My entire room was full of water SOURCE blocks. 

I hope this gives more info about the issue.

Still Good Luck !

Syths

**Comment by Pokefenn** [comment]
Actually, i just noticed you have Railcraft. There has been a bug for awhile with Railcrafts hidden heat blocks that causes blocks metadata to change, could be that. Trying replicating without Railcraft.

**Comment by F4ble2** [comment]
ok i will try it without Railcraft

edit: Railcraft is the Culprit without it works fine for me

**Comment by Pokefenn** [comment]
Thought so, Covert dun goofin. :/

**Comment by darthvader45** [comment]
Weird, I have this bug with Chisel blocks, and no Railcraft.  The major mods I have are TiCon, Thermal Expansion, Thaumcraft, MFR.
