### ISSUE TITLE
compatibility bug? (1.7.10 build 1.5.6b)

### ISSUE THREAD

**Issue by Cronosus** [Pokefenn/Chisel#41]
hello, i have this errors on loading game
http://pastebin.com/tZngeLTq

**Comment by Cronosus** [comment]
AdvancedSolarPanel, appliedenergistics2, AsieLib, backpacks, bibliocraft, biomesoplenty, BWG4, codechickencore, COFHcore, computercraft, extradoors, forgemultipart, gravestone, chatbubbles, chisel, IC2backpackhud,IC2nuclearcontrol2,immibiscore, IC2, lanteacraft, netherores, NEI, Railcraft, redlogic, secretroomsmod, statues, thermalexpansion, thermalfoundation

full load log:
http://pastebin.com/CjsrzGdk

**Comment by Lordmau5** [comment]
Is the game actually crashing or can you play?

Basically, those errors are there, because Chisel is trying to add compatibility for those mods.
It's searching for the desired class files of the mods, and apparently it spits out the _error_ because they are not installed / loaded.

**Comment by Cronosus** [comment]
not crashing, but i want eliminate all errors i have. ;)
.. for stabil modpack..

**Comment by Lordmau5** [comment]
Removed the stacktrace in #42 .
