### ISSUE TITLE
Block Suggestion actually.

### ISSUE THREAD

**Issue by smiletactician** [Pokefenn/Chisel#43]
Hey,

I was wondering if it were possible of the lava block have some extensions. Nothing big, Just that it has that nice black block but its the only one. Maybe, the rest of the lava blocks could also have the same texture options available?

**Comment by Pokefenn** [comment]
Suggestions like these are better left to the forum post rather than the bug tracker.

**Comment by smiletactician** [comment]
Thanks for replying. The BTP Github gets a messy so i've been a bit spoiled :D  And sometimes, just sometimes. Dev's are really hard to locate :D 

I hope I didn't convey any offence
smile
