### ISSUE TITLE
ClassNotFoundException in the console whilst loading the game

### ISSUE THREAD

**Issue by Painstouch** [Pokefenn/Chisel#49]
https://gist.github.com/Painstouch/c5f9add43f51133a24ea

**Comment by EoD** [comment]
- Does it also crash if you remove Chisel and keep NumiRP?
- Does it crash if you keep Chisel and remove NumiRP?

NumiRP seems to be from https://github.com/Numerios/NumiRP

**Comment by Painstouch** [comment]
It doesn't crash the game at all at the moment, it's just an excerpt from the console whilst loading the game.
Also, I don't have NumiRP installed, not that I am aware of or being able to see it in the mods section.

**Comment by ghost** [comment]
The error comes up because chisel is searching for the main mod class for compat's sake.  Don't worry about it- nothing went wrong.

**Comment by EoD** [comment]
Actually, this has already been fixed in b5d2c4aee28ebe0bf429ae51c2916c491c1c0a7c and a duplicate of #41 .

**Comment by Pokefenn** [comment]
Redundant "bug" report that people have "reported" loads of times already.
