### ISSUE TITLE
Missing Laboratory textures

### ISSUE THREAD

**Issue by EoD** [Pokefenn/Chisel#51]
@GravitasShortfall there seems to be an issue with your laboratory blocks. When I revert your commit 1fbb8ba6e520a2554aec49eb4e741421f69ddf14 , everything works fine.

```
[Client thread/ERROR] [FML/]: Caught exception from chisel
java.lang.RuntimeException: No valid textures found for chisel block variation 'Wall Panel', kind: 0, (laboratory/wallpanel)
    at info.jbcs.minecraft.chisel.carving.CarvableHelper.addVariation(CarvableHelper.java:132) ~[bin/:?]
    at info.jbcs.minecraft.chisel.carving.CarvableHelper.addVariation(CarvableHelper.java:68) ~[bin/:?]
    at info.jbcs.minecraft.chisel.ChiselBlocks.load(ChiselBlocks.java:1233) ~[bin/:?]
    at info.jbcs.minecraft.chisel.Chisel.preInit(Chisel.java:170) ~[bin/:?]
```

https://gist.github.com/EoD/17731d37c2c42212df71

**Comment by yschnellbach** [comment]
Strange, it ran fine when I tested it before the commit and still runs fine with my latest master branch (i.e. even with Pokefenn's master branch), so I can't reproduce it at the moment - so I'm slightly puzzled.

Are "wallpanel-cmtv.png" and "wallpanel-top.png" present in your ../assets/chisel/blocks/laboratory/ directory?

If they are present, can you try to swap them out with the attached ones (and see whether the error changes)?

![wallpanel-ctmv](https://cloud.githubusercontent.com/assets/7926955/4227447/95bc3870-3945-11e4-9027-eef78bc9db22.png)
![wallpanel-top](https://cloud.githubusercontent.com/assets/7926955/4227448/95c06b84-3945-11e4-854c-5d1ff0a11b74.png)

(these PNGs are indexed instead of full RGB. Upon inspection, I noticed that quite a lot of Chisel textures are indexed, so perhaps that's an issue that only pops up on certain configurations)

**Comment by EoD** [comment]
These are all the files I have which are starting with "wallpaper*" (there is no "cmtv", but a "ctmv"):

```
./src/main/resources/assets/chisel/textures/blocks/laboratory/wallpanel-ctmv.png: PNG image data32 32 8-bit/color RGB, non-interlaced
./src/main/resources/assets/chisel/textures/blocks/laboratory/wallpanel-top.png: PNG image data16 16 8-bit/color RGB, non-interlaced
```

Also the ones without "color RGB" give the same result. The other textures seem to range from "1-bit colormap" to "16-bit/color RGBA". I doubt that is the issue here.

**Comment by EoD** [comment]
Other textures are additionally located under "bin". Might that be the issue? Don't ask me how, though. ^^ 

```
./bin/assets/chisel/textures/blocks/sandstone-scribbles/scribbles-0-top.png
./src/main/resources/assets/chisel/textures/blocks/sandstone-scribbles/scribbles-0-top.png
```

**Comment by yschnellbach** [comment]
Sorry, yeah, I meant "ctmv", just a typo. So, paths and file naming convention are correct, hmmm...

What are you using to build it? I don't have a "./bin" directory at all when I run or compile it. I'm using gradle to build it, together with IntelliJ as per the instructions in the readme.

EDIT: You could always try copying the "laboratory" directory into "./bin/assets/chisel/textures/blocks/" and see whether that makes a difference - looks like they don't get copied into your ./bin directory while building (sorry, just can't quite pin it down where it's coming from as it builds/runs fine on my end, so I'm just poking around in the dark - always annoying to have a bug you can't reproduce yourself).

**Comment by EoD** [comment]
I am using the "GradleStart" method in eclipse. It seems to work fine with "./gradlew runClient" though. If I make a clean copy of the code the "bin" and "build" folders are empty, but on launching the client inside eclipse all textures except yours are being copied to the bin folder.

I found a piece of log in my server log from above which seems to miss the laboratory blocks: `[23:29:15] [Client thread/TRACE] [FML/]: Recursing into package assets`
Does that help in any way?

**Comment by yschnellbach** [comment]
It looks like it's not setting up your Eclipse workspace properly. I'm not at my machine atm (and for the next few hours), but a quick google ("GradleStart assets") suggest that that's a common issue.

Try a 'gradlew --refresh-dependencies setupDecompWorkspace' followed by 'gradlew eclipse'? That should update everything for your Eclipse workspace.

Also, does 'gradlew build' produce a working jar?

If that doesn't help, I'll try to set up the whole thing in Eclipse for myself when I have time to try and reproduce it.

**Comment by EoD** [comment]
You seem to be right, the `./gradlew setupDecompWorkspace --refresh-dependencies` refreshed my local assets caches.
It's odd that I have to force such a refresh when I am using a clean install.
