### ISSUE TITLE
Inconsistent item/block names

### ISSUE THREAD

**Issue by EoD** [Pokefenn/Chisel#54]
There are the following types of blocks/items in the Chisel mod:

```
chisel:tile.snakestoneSand
chisel:chisel.ice
chisel:chisel.chisel.stainedGlassPanePink
```
1. chisel:
2. chisel:chisel.
3. chisel:chisel.chisel.

I would like to make this naming consistent. Which of the three do you want to have? I am no expert, but the tutorials suggest to use the first type.

**Comment by yschnellbach** [comment]
Can this be done without breaking save compatibility? If not, not worth it, I think (before the 1.8 update).

**Comment by EoD** [comment]
Yes, I wouldn't have asked otherwise :)
See EoD/Chisel@b452a271a85d5ae9a6a297f48cdc5007323364bd .

**Comment by EoD** [comment]
If there are no further comments from @Pokefenn or any other developer, I am going with first case. It seems that almost all other mods are using this naming scheme in 1.7.10.

**Comment by yschnellbach** [comment]
Will this transition work for people with FMP configs, too? As FMP is, apart from making configs, black magic to me, I kind of doubt it has the provisions to provide re-mappings.

**Comment by EoD** [comment]
The naming scheme already changed from 1.5.5a to 1.5.5b or so. So it's not something very unsual to happen with this mod :/
I don't know how forge multipart works, so I can't really tell.

**Comment by EoD** [comment]
I worked on this a bit and this is the list I currently want to add: https://gist.github.com/EoD/feaf75ef1495e05886d7

All blocks have been renamed according to the forge naming scheme. Any objections/comments are appreciated. If I don't hear any comments in the next time, I will just go ahead and add the compatibility code.

**Comment by asiekierka** [comment]
Well, I approve.
