### ISSUE TITLE
Blocks cannot be broken with hand

### ISSUE THREAD

**Issue by EoD** [Pokefenn/Chisel#57]
You cannot break blocks with your handy anymore with 5ac0f459f7ac49a36bed117b332c872db88c2901 . After reverting this commit, everything works as normal.

@Lordmau5 I think you want to have a look at that

**Comment by Pokefenn** [comment]
Unable to reproduce, more info?

**Comment by EoD** [comment]
I tested it with b5816552db37a28b492c0d1e5becc06a1f14a972 and it didn't work.

You might also want to have a look at https://github.com/Pokefenn/Chisel/commit/ac3d6510bbeb8551d957b1b0a8c182124c898251#commitcomment-7784830

**Comment by EoD** [comment]
It works again in d562e842ddb258d7b08176695f346966151093cd . I can bisect the "fixing commit" if needed.
