### ISSUE TITLE
Broken Chiseled Neon Glowstone Gives Dust With Damage Value

### ISSUE THREAD

**Issue by psychofad** [Pokefenn/Chisel#8]
Was playing with the mod...chiseled a glowstone block to the neon glowstone..didn't like where it was at so i broke it...and it gave me glowstone dust with a damage value that couldn't be used in any recipes.  Should not have any damage values on the dust.  Thanks!

**Comment by Pokefenn** [comment]
Fixed in the latest commit. 
Thanks :)
