### ISSUE TITLE
Massive easi acces DUPE 1.6.4

### ISSUE THREAD

**Issue by Vycraftujto** [Pokefenn/Chisel#85]
Before you say you dont care about 1.6.4 remember that 1.6.4 servers are still big part of comunity.

EXAMPLE OF DUPE
https://www.youtube.com/watch?v=HE_oDgQJsYo

Please we be gratefull for fix

**Comment by Pokefenn** [comment]
I was gonna troll you really hard, but I'm not even gonna bother.
First off, there are many reasons why I wouldn't work with 1.6. One of them being that I don't even have the sourcecode that is used in the compiled version which is in most modpacks. Along with that its riddled with issues which just makes it unviable, and modders will vary rarely support things which are years old.

And to put the icing on the cake, the video you linked is in Russian. It's not very likely for a british teenager to know a word of Russian.
Not even going to go into the fact there isn't even a version number.
Oh yeah, and I don't even mod anymore.
At this point there is zero reason to be on 1.6, if you want a fix, find AUTOMATIC_MAIDENS source code, fix it and compile it for your server.

**Comment by Drullkus** [comment]
_facepalms_
